# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit animbook-journal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


## -----------------------------------------------------------------------------
library(animbook)
library(tidyverse)


## -----------------------------------------------------------------------------
example <- osiris |> 
  filter(country %in% c("AU", "US"),
                between(year, 2006, 2007)) |> 
  arrange(desc(sales)) 

example |> 
  filter(ID %in% c("US751825172", "US470731996", "AU004085330", "AU009134114", "AU009219809", "US161229730")) |> 
  reframe(ID, year, sales, country) |> 
  arrange(ID)


## -----------------------------------------------------------------------------
rank <- anim_prep(example, ID, sales, year, color = country)

rank$data |> 
  filter(id %in% c("US751825172", "US470731996", "AU004085330", "AU009134114", "AU009219809", "US161229730")) |> 
  rename(country = color) |> 
  select(-frame)


## -----------------------------------------------------------------------------
absolute <- anim_prep(example, ID, sales, year, color = country, scaling = "absolute")

absolute$data |> 
  filter(id %in% c("US751825172", "US470731996", "AU004085330", "AU009134114", "AU009219809", "US161229730")) |> 
  rename(country = color) |> 
  select(-frame)


## -----------------------------------------------------------------------------
rank_group <- anim_prep(example, ID, sales, year, color = country, group_scaling = country)

rank_group$data |> 
  filter(id %in% c("US751825172", "US470731996", "AU004085330", "AU009134114", "AU009219809", "US161229730")) |> 
  rename(country = group) |> 
  select(-c(frame, color))


## -----------------------------------------------------------------------------
absolute_group <- anim_prep(example, ID, sales, year, color = country, group_scaling = country, scaling = "absolute")

absolute_group$data |> 
  filter(id %in% c("US751825172", "US470731996", "AU004085330", "AU009134114", "AU009219809", "US161229730")) |> 
  rename(country = group) |> 
  select(-c(frame, color))


## ----data-diagram, fig.cap="The data transformation diagram."-----------------
knitr::include_graphics("figures/data-diagram.png")


## -----------------------------------------------------------------------------
animbook <- anim_prep(osiris, ID, sales, year)

animbook_cat <- anim_prep_cat(d_w_change, id, qnt, time)


## -----------------------------------------------------------------------------
# rank scaling
rank_scaling <- anim_prep(data = osiris, id = ID, values = sales, time = year)


## -----------------------------------------------------------------------------
# absolute scaling
absolute_scaling <- anim_prep(data = osiris, id = ID, values = sales, time = year, 
                              scaling = "absolute")


## -----------------------------------------------------------------------------
# rank scaling by group
rank_scaling_group <- anim_prep(data = osiris, id = ID, values = sales, time = year,
                                group_scaling = country)


## -----------------------------------------------------------------------------
# absoluate scaling by group
absolute_scaling_group <- anim_prep(data = osiris, id = ID, values = sales, time = year,
                                    group_scaling = country, scaling = "absolute")


## -----------------------------------------------------------------------------
animbook <- anim_prep_cat(data = d_w_change, id = id, values = qnt, time = time, color = gp)


## ----out.width="70%"----------------------------------------------------------
# kangaroo plot
kangaroo_plot(object = animbook,
              palette = RColorBrewer::brewer.pal(9, "Set1"), 
              rendering = "ggplot")


## ----out.width="70%"----------------------------------------------------------
# wallaby plot
wallaby_plot(object = animbook,
             group_palette = RColorBrewer::brewer.pal(9, "Set1"),
             shade_palette = RColorBrewer::brewer.pal(9, "Set1"),
             rendering = "ggplot",
             subset = "top",
             relation = "one_many",
             total_point = NULL)


## ----out.width="70%"----------------------------------------------------------
# funnel web plot
funnel_web_plot(object = animbook,
                palette = RColorBrewer::brewer.pal(9, "Set1"),
                rendering = "ggplot")


## -----------------------------------------------------------------------------
# animate <- anim_prep_cat(d_w_change, id = id, values = qnt, time = time, color = gp, time_dependent = FALSE)
# 
# p <- wallaby_plot(animate)
# 
# p2 <- anim_animate(p)
# 
# gganimate::anim_save("figures/dwchange.gif", p2)


## -----------------------------------------------------------------------------
# knitr::include_graphics("figures/dwchange.gif")


## -----------------------------------------------------------------------------
# raw_data <- read_csv("data-raw/osiris2021-sample1000.csv")

# filter the data with sales record in selected period (2009 - 2018)

# data <- raw_data |>
#   filter(year >= 2000 & year < 2020,
#         country %in% c("US", "JP", "CN")) |>
#   select(year, country, ID, sales) |>
#   filter(!is.na(sales) & sales != 0)
# 
# country <- data |>
#   select(ID, country) |>
#   distinct()
# 
# # complete the data using complete function for the missing year
# complete_data <- data |>
#   select(-country) |>
#   tidyr::complete(year, ID) |>
#   left_join(country) |>
#   mutate(ID = as.factor(ID),
#         year = as.integer(year))
# 
# label <- c("Top 25%", "25-50", "50-75", "75-100", "Not listed")
# 
# animbook <- anim_prep(osiris, ID, sales, year, label = label, ngroup = 4, color = country, time_dependent = FALSE)
# 
# ptop <- wallaby_plot(animbook, subset = "bottom", relation = "many_one", total_point = 500)
# 
# ptop2 <- anim_animate(ptop)
# 
# gganimate::animate(ptop2)
# 
# pbottom <- wallaby_plot(osiris, subset = "bottom", relation = "one_many", total_point = 500)
# 
# pbottom2 <- anim_animate(pbottom)
# 
# gganimate::animate(pbottom2)
# 
# gganimate::anim_save("inst/new_visualisation/exit.gif", ptop2, height = 8,
#                      width = 9, units = "in", res = 150)
# 
# gganimate::anim_save("inst/new_visualisation/enter.gif", pbottom2, height = 8,
#                      width = 9, units = "in", res = 150)


## -----------------------------------------------------------------------------
# object <- anim_prep_cat(data = aeles,
#                         id = id,
#                         values = party,
#                         time = year,
#                         color = gender,
#                         order = NULL,
#                         time_dependent = FALSE)
# 
# # subset can be either "top", "bottom" or values in the data
# # many_one not working yet
# 
# p <- wallaby_plot(object = object,
#                   group_palette = RColorBrewer::brewer.pal(9, "Set1"),
#                   shade_palette = RColorBrewer::brewer.pal(9, "Set1"),
#                   rendering = "ggplot",
#                   subset = "top",
#                   relation = "one_many",
#                   height = 1,
#                   size = 3,
#                   width = 100,
#                   total_point = 1000)
# 
# p2 <- anim_animate(p)
# 
# gganimate::animate(p2)

