# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit animbook-journal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)


## -----------------------------------------------------------------------------
library(animbook)
library(tidyverse)


## ----data-diagram, fig.cap="The diagram shows what are the expected data forms.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page"----
knitr::include_graphics("figures/data-diagram.png")


## ----animation-diagram, fig.cap="The diagram shows how the animation is done using the successive pictures.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page"----
knitr::include_graphics("figures/animation-diagram.png")


## ----animated-diagram, fig.cap="The diagram shows how the frames were used in the animated plot.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page"----
knitr::include_graphics("figures/animated-diagram.png")


## ----proportional-shade, fig.show="hold", out.width="50%", fig.cap="The plot shows the difference between the sigmoid and sine curves."----
knitr::include_graphics("figures/sigmoid-shade.png")
knitr::include_graphics("figures/sine-shade.png")


## -----------------------------------------------------------------------------
dbl_change |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  reframe(id, time, values, gp) |> 
  arrange(gp, id)


## -----------------------------------------------------------------------------
rank <- anim_prep(dbl_change, id, values, time, color = gp) 

rank$data |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = color) |> 
  select(-frame) |> 
  arrange(gp, id)


## -----------------------------------------------------------------------------
absolute <- anim_prep(dbl_change, id, values, time, color = gp, scaling = "absolute") 

absolute$data |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |>  
  rename(gp = color) |> 
  select(-frame) |> 
  arrange(gp, id)


## -----------------------------------------------------------------------------
rank_group <- anim_prep(dbl_change, id, values, time, color = gp, group_scaling = gp) 

rank_group$data |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = group) |> 
  select(-c(frame, color)) |> 
  arrange(gp, id)


## -----------------------------------------------------------------------------
absolute_group <- anim_prep(dbl_change, id, values, time, color = gp, group_scaling = gp, scaling = "absolute") 

absolute_group$data |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = group) |> 
  select(-c(frame, color)) |> 
  arrange(gp, id)


## ----shade-algorithm, fig.show="hold", out.width="50%", fig.cap="The plot shows how does the algorithm work."----
knitr::include_graphics("figures/sankey-shade-1.png")
knitr::include_graphics("figures/sankey-shade-2.png")


## ----echo=TRUE----------------------------------------------------------------
animbook <- anim_prep_cat(cat_change, 
                          id = id, 
                          values = qnt, 
                          time = time, 
                          color = gp, 
                          time_dependent = FALSE)

head(animbook$data, 10)
str(animbook)


## ----echo=TRUE, fig.width=8, fig.align='center', out.width="100%", layout = "l-page"----
p <- wallaby_plot(object = animbook,
             group_palette = RColorBrewer::brewer.pal(9, "Set1"),
             shade_palette = c("#737373", "#969696", "#BDBDBD","#D9D9D9","#D9D9D9","#D9D9D9"),
             rendering = "ggplot",
             subset = "top",
             relation = "one_many",
             total_point = NULL)

p


## ----eval=FALSE---------------------------------------------------------------
#> p2 <- anim_animate(p)
#> 
#> gganimate::anim_save("figures/catchange.gif", p2)


## ----catchange-figure, fig.cap = "Animate visualization using example data.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-example.png")


## ----catchange-gif, out.extra="class = 'gif'", fig.cap = "Animate visualization using example data.", eval=knitr::is_html_output()----
#> knitr::include_graphics("figures/catchange.gif")


## ----echo=TRUE----------------------------------------------------------------
data <- osiris |> 
  filter(country %in% c("US", "JP"))

label <- c("Top 25%", "25-50", "50-75", "75-100", "Not listed")

accounting <- anim_prep(data, 
                      id = ID, 
                      values = sales, 
                      time = year, 
                      label = label, 
                      ngroup = 4, 
                      color = country, 
                      time_dependent = FALSE)

p <- wallaby_plot(accounting,
                  group_palette = RColorBrewer::brewer.pal(9, "Set1"),
                  shade_palette = c("#737373", "#969696", "#BDBDBD","#D9D9D9","#D9D9D9","#D9D9D9"),
                  subset = "bottom",
                  relation = "many_one",
                  height = 1,
                  size = 2,
                  width = 100,
                  total_point = 1000)

p2 <- anim_animate(p)


## ----eval=FALSE---------------------------------------------------------------
#> gganimate::anim_save("figures/exit.gif", p2, height = 8, fps = 30,
#>                      nframes = 400, width = 9, units = "in", res = 150)


## ----osiris-figure, fig.cap = "The animate visualization shows the companies that exited the market.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-exit.png")


## ----osiris-gif, out.extra="class = 'gif'", fig.cap = "The animate visualization shows the companies that exited the market.", eval=knitr::is_html_output()----
#> knitr::include_graphics("figures/exit.gif")


## ----echo=TRUE----------------------------------------------------------------
voter <- anim_prep_cat(data = aeles,
                       id = id,
                       values = party,
                       time = year,
                       color = gender,
                       order = NULL,
                       time_dependent = FALSE)

p_voter <- wallaby_plot(object = voter,
                  group_palette = RColorBrewer::brewer.pal(9, "Set1"),
                  shade_palette = c("#737373", "#969696", "#BDBDBD","#D9D9D9","#D9D9D9","#D9D9D9"),
                  rendering = "ggplot",
                  subset = "top",
                  relation = "one_many",
                  height = 1,
                  size = 2,
                  width = 100,
                  total_point = 1000)

p2_voter <- anim_animate(p_voter)


## ----eval=FALSE---------------------------------------------------------------
#> gganimate::anim_save("figures/voter.gif", p2_voter, height = 8, fps = 30,
#>                      nframes = 400, width = 9, units = "in", res = 150)


## ----voter-figure, fig.cap = "The animate visualization shows how does the top party perform in keeping the old  voters for different genders.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-voter.png")


## ----voter-gif, out.extra="class = 'gif'", fig.cap = "The animate visualization shows how does the top party perform in keeping the old  voters for different genders.", eval=knitr::is_html_output()----
#> knitr::include_graphics("figures/voter.gif")

