# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit animbook-journal.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)


## -----------------------------------------------------------------------------
library(animbook)
library(tidyverse)


## ----nyt, fig.cap="Screenshot of the New York Times animation, which is the motivation for this visualization package. The animation illustrates the disparity between white men and black men. It reveals that despite black boys growing up in a rich household, they still have a higher likelihood of falling into lower income groups compared to white boys.", fig.width=8, fig.align='center', out.width="100%", layout = "l-body"----
knitr::include_graphics("figures/NYT.png")


## ----data-diagram, fig.cap="The animation expects data with an ID and a time variable, along with a numerical variable (raw form), which is possibly converted to categorical (categorized). The data can be provided in the raw or categorized form and will be processed into the format needed for the animation, where the categorical variable is treated as a quantile and an animation frame variable is created.", fig.width=8, fig.align='center', out.width="100%", layout = "l-body"----
knitr::include_graphics("figures/data-diagram.png")


## ----animation-diagram, fig.cap="An animation requires small changes shown in quick succession to make it appear as if the objects are in motion. The three plots above show a single point changing position by a small amount, which when shown quickly, will look like that point has moved up and to the right.", fig.width=8, fig.align='center', out.width="100%", layout = "l-body"----
knitr::include_graphics("figures/animation-diagram.png")


## ----animated-diagram, fig.cap="Frames 1 and 2 show the year 1 and year 2 positions of points from the data in the table at the top. The id is necessary to enable interpolation to make the small changes to generate a perception of motion from frame 1 position to frame 2 position.", fig.width=8, fig.align='center', out.width="100%", layout = "l-body"----
knitr::include_graphics("figures/animated-diagram.png")


## ----proportional-shade, fig.show="hold", out.width="50%", fig.cap="The plot shows the difference between the sigmoid (left) and the sine curve (right). In the sigmoid, as the curve progresses, it appears to become narrower, possibly resulting in more misperception of relative proportions compared to the sine curve."----
knitr::include_graphics("figures/sigmoid-shade.png")
knitr::include_graphics("figures/sine-shade.png")


## -----------------------------------------------------------------------------
original <- dbl_change |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  reframe(id, time, values, gp) |> 
  arrange(gp, id)

rank <- anim_prep(dbl_change, id, values, time, 
                  group = gp) 

class(rank) <- c("tbl_df", "tbl", "data.frame")

rank_data <- rank |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = group,
         rank = qtile) |>  
  arrange(gp, id)

absolute <- anim_prep(dbl_change, id, values, time, 
                      group = gp, 
                      scaling = "absolute") 

class(absolute) <- c("tbl_df", "tbl", "data.frame")

absolute_data <- absolute |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |>  
  rename(gp = group,
         absolute = qtile) |> 
  arrange(gp, id)

rank_group <- anim_prep(dbl_change, id, values, time, 
                        group = gp, 
                        group_scaling = gp) 

class(rank_group) <- c("tbl_df", "tbl", "data.frame")

rank_group_data <- rank_group |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = group,
         rank_group = qtile) |> 
  arrange(gp, id)

absolute_group <- anim_prep(dbl_change, id, values, time, 
                            group = gp, 
                            group_scaling = gp, 
                            scaling = "absolute") 

class(absolute_group) <- c("tbl_df", "tbl", "data.frame")

absolute_group_data <- absolute_group |> 
  filter(id %in% c(1, 14, 21, 100, 106, 148)) |> 
  rename(gp = group,
         absolute_group = qtile) |> 
  arrange(gp, id)


## -----------------------------------------------------------------------------
scaling_table <- original |> 
  left_join(rank_data, by = c("id", "time", "gp")) |> 
  left_join(rank_group_data, by = c("id", "time", "gp")) |> 
  left_join(absolute_data, by = c("id", "time", "gp")) |> 
  left_join(absolute_group_data, by = c("id", "time", "gp")) |> 
  reframe(id, time, gp, values, rank, rank_group, absolute, absolute_group)


## ----tbl-scaling, eval=knitr::is_html_output()--------------------------------
# scaling_table |>
#   knitr::kable(caption = "A summary of different scaling methods applied to the dataset.")


## ----tbl-scaling-la, eval=knitr::is_latex_output()----------------------------
scaling_table |> 
  knitr::kable(caption = "A summary of different scaling methods applied to the dataset.") |> 
  kableExtra::column_spec(2, width = "30em")


## -----------------------------------------------------------------------------
argument_num <- c("data", "id", "values", "time", "group", "ncat", "breaks", "label", 
              "group_scaling", "scaling")

description_num <- c("The numerical data to be prepared for visualization.",
                     "The column name in the data that will be used to identify an individual over time. For example, company name.",
                     "The column name in the data that will be used for the y-axis (must be numerical).",
                     "The column name in the data represents the time variable (x-axis).",
                     "The column name in the data for distinguishes between the values group (for example, country). In the visualization, this will be used as a color argument.",
                     "The number of categories to create for scaling values. The default for this function is 5 categories.",
                     "A vector of breaks for creating bins. If this is not provided, the bins will have equal size.",
                     "A vector of labels to be used for the y-axis in the visualization. If this is not provided, the labels will be the position on the y-axis.",
                     "The column name in the data that will be used for grouping. Allow the function to isolate the calculation between the groups.",
                     "The scaling method to be used; \"rank\" or \"absolute\". The default scaling is \"rank\".") 

argument_num_tab <- tibble::tibble(Argument = argument_num,
                                   Description = description_num)


## -----------------------------------------------------------------------------
argument_cat <- c("data", "id", "values", "time", "group", "order", "label")

description_cat <- c("The data that contains the values in the categorized format.",
                     "The column name in the data that will be used to identify an individual over time. For example, election parties.",
                     "The column name in the data that will be used for the y-axis (must be a factor).",
                     "The column name in the data represents the time variable (x-axis).",
                     "The column name in the data for distinguishes between the values group (for example, gender). In the visualization, this will be used as a color argument.",
                     "A vector of order for sorting the category values. If this is not provided, it will be arranged based on the number of observations (largest to smallest).",
                     "A vector of labels to be used for the y-axis in the visualization. If this is not provided, the labels will be the position on the y-axis.")

argument_cat_tab <- tibble::tibble(Argument = argument_cat,
                                   Description = description_cat)


## ----tbl-num, eval=knitr::is_html_output()------------------------------------
# argument_num_tab |>
#   knitr::kable(caption = "The arguments for the anim\\_prep function.")


## ----tbl-num-la, eval=knitr::is_latex_output()--------------------------------
argument_num_tab |> 
  kableExtra::kable(caption = "The arguments for the anim\\_prep function.", format = "latex") |> 
  kableExtra::column_spec(2, width = "30em")


## ----tbl-cat, eval=knitr::is_html_output()------------------------------------
# argument_cat_tab |>
#   knitr::kable(caption = "The arguments for the anim\\_prep\\_cat function.")


## ----tbl-cat-la, eval=knitr::is_latex_output()--------------------------------
argument_num_tab |> 
  kableExtra::kable(caption = "The argumenst for the anim\\_prep\\_cat function.", format = "latex") |> 
  kableExtra::column_spec(2, width = "30em")


## -----------------------------------------------------------------------------
argument2 <- c("data", "group_palette", "shade_palette", "rendering", "time_dependent",
               "subset", "relation", "total_point", "height", "width", "size",
               "alpha")

description2 <- c("The categorized data returned from the prep function.",
                  "The vector of the palette used by the function to supply the color to each group.",
                  "The vector of the palette used by the function to supply the color to the shaded area.",
                  "The choice of method used to create and display the plot, either gganimate or plotly. Default is gganimate.",
                  "Should the observations entered the visualization at the same time. Default is FALSE",
                  "A character string specifying the variable used for subsetting the data. The \"top\" and \"bottom\" strings can also be used in this argument. Default is \"top\".",
                  "The choice of relationship for the values to display on the plot, either \"one_many.\" or \"many_one\". Default is \"one_many\".",
                  "The number of points the users want for the wallaby plot. Default is NULL, which is the number of points equal to the original.",
                  "The proportion of the area occupied by the observations in the shaded areas. Default is 0.6.",
                  "The distance between the first and last observation in the animation. Default is 50.",
                  "The point size. Default is 2.",
                  "The opacity of the proportional shaded areas. Default is 0.1.")

argument_table2 <- tibble::tibble(Argument = argument2,
                                  Description = description2)


## ----eval=knitr::is_html_output()---------------------------------------------
# argument_table2 |>
#   knitr::kable(caption = "The arguments for the wallaby\\_plot function.")


## ----eval=knitr::is_latex_output()--------------------------------------------
argument_table2 |> 
  kableExtra::kable(caption = "The arguments for the wallaby\\_plot function.", format = "latex") |> 
  kableExtra::column_spec(2, width = "30em")


## ----echo=TRUE----------------------------------------------------------------
a <- anim_prep_cat(cat_change, 
                   id = id, 
                   values = qnt, 
                   time = time, 
                   group = gp)
class(a)
glimpse(a)


## ----top-one, echo=TRUE, fig.width=8, fig.align='center', out.width="100%", layout = "l-body", fig.cap="This illustrates the transition of points from the left category A to the right categories A and E. This is also referred to as a one-to-many relationship plot. The points shown in this plot only originated in category A. It emphasizes that these points only stay within the same category A or change to category E."----
p <- wallaby_plot(data = a,
                  group_palette = RColorBrewer::brewer.pal(9, "Set1"),
                  rendering = "gganimate",
                  subset = "top",
                  relation = "one_many",
                  total_point = NULL)

p


## ----top-many, echo=TRUE, fig.width=8, fig.align='center', out.width="100%", layout = "l-body", fig.cap="The plot shows the movement of points from categories A and E on the right to category A on the left, representing a many-to-one relationship. This specifically highlights the points that have moved to category A, which are the points that originate from categories A and E."----
p_2 <- wallaby_plot(data = a,
                    rendering = "gganimate",
                    subset = "top",
                    relation = "many_one",
                    total_point = NULL)

p_2


## ----b-many, echo=TRUE, fig.width=8, fig.align='center', out.width="100%", layout = "l-body", fig.cap="The plot shows the transfer of points from the right category B to the left category B. It underscores that the points ultimately landing in category B originate specifically from category B itself."----
p_3 <- wallaby_plot(data = a,
                    rendering = "gganimate",
                    subset = "B",
                    relation = "many_one",
                    total_point = NULL)

p_3


## ----eval=FALSE---------------------------------------------------------------
# p2 <- anim_animate(p)
# 
# gganimate::anim_save("figures/catchange.gif", p2, height = 8, fps = 30,
#                      nframes = 400, width = 9, units = "in", res = 150)


## ----catchange-figure, fig.cap = "Four single frames from the animated visualization using example data. All of the X observations stay within the same group, while Y observations change from group A to group E.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-example.png")


## ----catchange-gif, fig.cap = "Animated visualization using example data. All of the X observations stay within the same group, while some of the Y observations change from group A to group E.", eval=knitr::is_html_output()----
# knitr::include_url("https://www.youtube.com/embed/j-azl7vKjwo")


## ----echo=TRUE----------------------------------------------------------------
# library(animbook)
# library(dplyr)

data <- osiris |> 
  filter(country %in% c("US", "JP"))

label <- c("Top 25%", "25-50", "50-75", "75-100", "Not listed")

accounting <- anim_prep(data, 
                      id = ID, 
                      values = sales, 
                      time = year, 
                      label = label, 
                      ncat = 4, 
                      group = country)

kan_p <- kangaroo_plot(accounting)

p <- wallaby_plot(accounting,
                  subset = "bottom",
                  relation = "many_one",
                  height = 1,
                  size = 2,
                  width = 100,
                  total_point = 1000)

kan_p2 <- anim_animate(kan_p)

p2 <- anim_animate(p)


## ----eval=FALSE---------------------------------------------------------------
# gganimate::anim_save("figures/exit.gif", p2, height = 8, fps = 30,
#                      nframes = 400, width = 9, units = "in", res = 150)
# 
# gganimate::anim_save("figures/kan-osiris.gif", kan_p2, height = 8, fps = 10,
#                      nframes = 400, width = 9, units = "in", res = 150)


## ----kan-osiris-figure, fig.cap = "Four frames from the kangaroo plot visualization showing the movement of the Japanese and US companies between the performance sales quantiles from 2006 to 2018 for a sample of data extracted from the Osiris database. The 'not listed' category indicates companies not yet listed or removed from the listing. Most companies stay in the same quantile group, with a small number moving up and down. Most of the movement is made by American companies, which supports the OECD report that US companies have a higher turnover rate relative to Japanese companies.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/osiris.png")


## ----kan-osiris-gif, fig.cap = "The kangaroo plot visualization shows the movement of the Japanese and US companies between the performance sales quantiles from 2006 to 2018 for a sample of data extracted from the Osiris database. The 'not listed' category indicates companies not yet listed or removed from the listing. Most companies stay in the same quantile group, with a small number moving up and down. Most of the movement is made by American companies, which supports the OECD report that US companies have a higher turnover rate relative to Japanese companies.", eval=knitr::is_html_output()----
# knitr::include_url("https://www.youtube.com/embed/xB9DK5efEL8")


## ----osiris-figure, fig.cap = "The wallaby plot visualization shows the companies that exited the market. There are more United States companies that fall down into a not listed group (got de-listed) compared to Japanese companies.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-exit.png")


## ----osiris-gif, fig.cap = "The wallaby plot visualization shows the companies that exited the market. There are more United States companies that fall down into a not listed group (got de-listed) compared to Japanese companies.", eval=knitr::is_html_output()----
# knitr::include_url("https://www.youtube.com/embed/TIWtFf6KaCI")


## -----------------------------------------------------------------------------
aeles <- aeles |> 
  filter(party != "other")


## ----echo=TRUE----------------------------------------------------------------
voter <- anim_prep_cat(data = aeles,
                       id = id,
                       values = party,
                       time = year,
                       group = gender,
                       order = NULL)

p_voter <- wallaby_plot(data = voter,
                  group_palette = c("pink", "blue", "red"),
                  shade_palette = c("#737373", "#969696", "#BDBDBD",
                                    "#D9D9D9","#D9D9D9","#D9D9D9"),
                  rendering = "gganimate",
                  subset = "top",
                  relation = "one_many",
                  height = 1,
                  size = 2.5,
                  width = 100,
                  total_point = 1000)

p2_voter <- anim_animate(p_voter)


## ----eval=FALSE---------------------------------------------------------------
# gganimate::anim_save("figures/voter.gif", p2_voter, height = 8, fps = 30,
#                      nframes = 400, width = 9, units = "in", res = 150)


## ----voter-figure, fig.cap = "Four frames from a wallaby plot visualization show how the top party performs in keeping the old voters of different genders. Most voters remain loyal to the party, but a small fraction of voters with roughly equal male-to-female ratio switch primarily to the other major party. Interestingly, the few individuals who identified as neither male nor female overwhelmingly shifted their party affiliations to the Greens.", fig.width=8, fig.align='center', out.width="100%", layout = "l-page", eval=knitr::is_latex_output()----
knitr::include_graphics("figures/animation-voter.png")


## ----voter-gif, fig.cap = "The wallaby plot visualization shows how the top party performs in keeping the old voters of different genders. Most voters remain loyal to the party, but a small fraction of voters with roughly equal male-to-female ratio switch primarily to the other major party. Interestingly, the few individuals who identified as neither male nor female overwhelmingly shifted their party affiliations to the Greens.", eval=knitr::is_html_output()----
# knitr::include_url("https://www.youtube.com/embed/6afmJ0sxvtc")

